name: example_with_integration_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.3 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^4.1.1
  json_annotation: ^4.0.1
  rxdart: ^0.26.0
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  flutter_simple_dependency_injection: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  flutter_gherkin:
    path: ../

flutter:

  uses-material-design: true