name: example_with_integration_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.3 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  uuid: ^3.0.7
  flutter_simple_dependency_injection: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner:
  flutter_gherkin: 3.0.0-rc.17

flutter:

   uses-material-design: true
